server {
	server_name localhost;
	listen 1234;
	client_body_size 1000000;
	index index.html;
	#root images;
	error_page 404 error_pages/404.html;
	error_page 401 error_pages/401.html;

	location /test {
		allow_methods GET DELETE POST;
		autoindex on;
	}
	location /test/oi {
		allow_methods GET POST;
		autoindex off;
	}
	location / {
		index text.html;#
		allow_methods  DELETE POST;
		root images; #check
		autoindex off;
		#root /root;
	}
}
